  [[main]]
  name = "Accueil"
  identifier = "accueil"
  weight = 100
  url = "/"

  [[main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[main]]
  name = "Portfolio"
  weight = 300
  identifier = "portfolio"
  url = "/portfolio/"

  [[main]]
  name = "A propos"
  weight = 400
  identifier = "a propos"
  url = "/a propos/"

  [[main]]
  name = "Documents"
  weight = 500
  identifier = "documents"

  [[main]]
  name = "CV"
  weight = 510
  identifier = "cv"
  url = "/cv/"
  parent = "documents"  

  [[main]]
  name = "Certifications"
  weight = 520
  identifier = "certifications"
  url = "/certifications/"
  parent = "documents"

  [[main]]
  name = "Contact"
  weight = 600
  identifier = "contact"
  url = "/contact/"

  [[footer]]
  name = "imprint"
  weight = 1
  identifier = "imprint"
  url = "/imprint/"